### PR TITLE
Ruined @cshinaver's theme

### PR DESCRIPTION
**Pull request by JohnathonNow**
I'm sorry @cshinaver, but it had to be done.

image
image

### CODE REVIEW

**Comment by pbui** [comment]
The colors look fine.  I think we still need to work on the layout, particularly the landing page.  For now, this is an acceptable incremental change.

**Comment by AndrewLitteken** [comment]
I agree with Bui, colors are fine, some text and layout changes probably to come

**Comment by bdevorem** [comment]
Should there be a general landing page, and then a navbar tab for the blog posts? 
I'd also like to see a page where posts are grouped by tag, or just a page with all the tags.

Also, the font hurts my eyes.

**Comment by keylime-unicorn** [comment]
Colors are fine. Not a fan of the layout.

**Pull request merged**
