### PR TITLE
100% improved product

### PR DESCRIPTION
**Pull request by JohnathonNow**
A landing page.

### CODE REVIEW

**Comment by JohnathonNow** [comment]
image

**Comment by JohnathonNow** [comment]
image

**Comment by wbadart** [comment]
Thoughts on some padding between the News and Contact columns (`.column1` and `.column2`)? Feels crowded. Love the screenfetch (except for the lack of zsh love)

**Comment by AndrewLitteken** [comment]
I agree on the spacing between the columns
Can we capitalize things?
OS: Highly Varied
New Year's Resolution: A better blog
etc

**Comment by AndrewLitteken** [comment]
Ok, one more thing, I just didn't catch it before:
New Year's Resolution

**Comment by JohnathonNow** [comment]
Good?

**Comment by AndrewLitteken** [comment]
I think it looks good

**Pull request merged**
